"""add_gastos_fijos_table

Revision ID: aea2c9ce9817
Revises: da72b3e27f40
Create Date: 2025-06-18 13:28:39.379693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aea2c9ce9817'
down_revision: Union[str, None] = 'da72b3e27f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
