"""add_multiple_treatments_and_credit_card_support

Revision ID: b1d113bea618
Revises: aea2c9ce9817
Create Date: 2025-06-19 13:31:46.787425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1d113bea618'
down_revision: Union[str, None] = 'aea2c9ce9817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create recordtreatment table for multiple treatments per record
    op.create_table('recordtreatment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('record_id', sa.Integer(), nullable=False),
        sa.Column('treatment_id', sa.Integer(), nullable=True),
        sa.Column('nombre_tratamiento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('precio_normal', sa.Float(), nullable=False),
        sa.Column('precio_promocional', sa.Float(), nullable=False),
        sa.Column('costo_unitario', sa.Float(), nullable=False),
        sa.Column('ganancia_individual', sa.Float(), nullable=False),
        sa.Column('orden', sa.Integer(), nullable=False, default=1),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
        sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add new columns to record table for multiple treatments support
    with op.batch_alter_table('record') as batch_op:
        # Make treatment_id nullable for multiple treatments records
        batch_op.alter_column('treatment_id', nullable=True)
        
        # Add multiple treatments fields
        batch_op.add_column(sa.Column('nombre_promocion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('precio_normal_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ahorro_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tiene_multiples_tratamientos', sa.Boolean(), nullable=False, default=False))
        
        # Add enhanced credit card fields
        batch_op.add_column(sa.Column('numero_autorizacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('ultimos_4_digitos', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove new columns from record table
    with op.batch_alter_table('record') as batch_op:
        batch_op.drop_column('ultimos_4_digitos')
        batch_op.drop_column('numero_autorizacion')
        batch_op.drop_column('tiene_multiples_tratamientos')
        batch_op.drop_column('ahorro_total')
        batch_op.drop_column('precio_normal_total')
        batch_op.drop_column('nombre_promocion')
        
        # Restore treatment_id as not nullable
        batch_op.alter_column('treatment_id', nullable=False)
    
    # Drop recordtreatment table
    op.drop_table('recordtreatment')
    
    # ### end Alembic commands ###
