"""add_notification_system_tables

Revision ID: d0b4912ed785
Revises: b1d113bea618
Create Date: 2025-06-20 16:15:37.423712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd0b4912ed785'
down_revision: Union[str, None] = 'b1d113bea618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'treatment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('record', 'precio_normal_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('record', 'ahorro_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('record', 'tiene_multiples_tratamientos',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_record_metodo_pago'), table_name='record')
    op.drop_index(op.f('idx_record_multiples'), table_name='record')
    op.drop_index(op.f('idx_recordtreatment_record_id'), table_name='recordtreatment')
    op.drop_index(op.f('idx_recordtreatment_treatment_id'), table_name='recordtreatment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_recordtreatment_treatment_id'), 'recordtreatment', ['treatment_id'], unique=False)
    op.create_index(op.f('idx_recordtreatment_record_id'), 'recordtreatment', ['record_id'], unique=False)
    op.create_index(op.f('idx_record_multiples'), 'record', ['tiene_multiples_tratamientos'], unique=False)
    op.create_index(op.f('idx_record_metodo_pago'), 'record', ['metodo_pago'], unique=False)
    op.alter_column('record', 'tiene_multiples_tratamientos',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('record', 'ahorro_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('record', 'precio_normal_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('record', 'treatment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
