"""add payment fields to records

Revision ID: da72b3e27f40
Revises: 
Create Date: 2025-06-10 18:25:28.509862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da72b3e27f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('costo_unitario', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('record', sa.Column('ganancia', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('record', sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='efectivo'))
    op.add_column('record', sa.Column('tipo_tarjeta', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('record', sa.Column('meses_sin_intereses', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('tasa_comision', sa.Float(), nullable=True))
    op.add_column('record', sa.Column('comision_monto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'comision_monto')
    op.drop_column('record', 'tasa_comision')
    op.drop_column('record', 'meses_sin_intereses')
    op.drop_column('record', 'tipo_tarjeta')
    op.drop_column('record', 'metodo_pago')
    op.drop_column('record', 'ganancia')
    op.drop_column('record', 'costo_unitario')
    # ### end Alembic commands ###
